import { Delta } from "@block-kit/delta";

export const TARGET_DELTA = new Delta([
  { insert: "测试文档" },
  { insert: "\n", attributes: { heading: "h1" } },
  { insert: "初始多行文本内容" },
  { insert: "\n" },
  { insert: "初始多行文本内容" },
  { insert: "\n" },
  { insert: "初始多行文本内容" },
  { insert: "\n" },
  { insert: "二级标题" },
  { insert: "\n", attributes: { heading: "h2" } },
  { insert: "加粗文本", attributes: { bold: "true" } },
  { insert: " " },
  { insert: "斜体文本", attributes: { italic: "true" } },
  { insert: " " },
  { insert: "删除线", attributes: { del: "true" } },
  { insert: "\n" },
  { insert: "三级标题" },
  { insert: "\n", attributes: { heading: "h3" } },
  { insert: "无序列表项1" },
  { insert: "\n", attributes: { bullet: "true", level: "1" } },
  { insert: "无序列表项1.1" },
  { insert: "\n", attributes: { bullet: "true", level: "2" } },
  { insert: "无序列表项1.2" },
  { insert: "\n", attributes: { bullet: "true", level: "2" } },
  { insert: "无序列表项2" },
  { insert: "\n", attributes: { level: "1", bullet: "true" } },
  { insert: "四级标题" },
  { insert: "\n", attributes: { heading: "h4" } },
  { insert: "有序列表A" },
  { insert: "\n", attributes: { ordered: "true", level: "1", index: "1" } },
  { insert: "有序列表B" },
  { insert: "\n", attributes: { ordered: "true", level: "1", index: "2" } },
  { insert: "行内代码", attributes: { "inline-code": "true" } },
  { insert: " 和 " },
  { insert: "链接", attributes: { href: "https://example.com", link: "true" } },
  { insert: "\n" },
  { insert: "\n" },
]);
